"""Add customizado_amortizacao to Contrato

Revision ID: 1143c7e56630
Revises: 3dcaee2b184e
Create Date: 2025-06-27 14:57:44.075000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1143c7e56630'
down_revision = '3dcaee2b184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customizado_amortizacao', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('customizado_amortizacao')

    # ### end Alembic commands ###
