"""Estrutura inicial

Revision ID: 3dcaee2b184e
Revises: 
Create Date: 2025-06-27 14:51:31.102911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcaee2b184e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('taxa_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato', sa.String(length=50), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('instituicao', sa.String(length=100), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_devedor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('indexador', sa.String(length=50), nullable=True),
    sa.Column('juros_pre', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('juros_spread', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('juros_anual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('juros_mensal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('parcela', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qtd_parcela', sa.Integer(), nullable=True),
    sa.Column('parc_paga', sa.Integer(), nullable=True),
    sa.Column('parc_pendente', sa.Integer(), nullable=True),
    sa.Column('principal_pago', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('principal_pendente', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('juros_pago', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('juros_pendente', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('curto_pz', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('longo_pz', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('erp', sa.String(length=50), nullable=True),
    sa.Column('carencia_juros', sa.Integer(), nullable=True),
    sa.Column('carencia_principal', sa.Integer(), nullable=True),
    sa.Column('prazo_meses', sa.Integer(), nullable=True),
    sa.Column('data_rescisao', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=True),
    sa.Column('iof', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tac', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('outros', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('modalidade', sa.String(length=50), nullable=True),
    sa.Column('sistema_amortizacao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    op.drop_table('user')
    op.drop_table('taxa_referencia')
    op.drop_table('produto')
    op.drop_table('log_sistema')
    # ### end Alembic commands ###
