"""empresa_id em contrato e tabela empresa

Revision ID: 7c78875a6f8e
Revises: a5aa13136de9
Create Date: 2025-06-30 17:15:24.502869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c78875a6f8e'
down_revision = 'a5aa13136de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_contrato_empresa', 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_contrato_empresa', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    op.drop_table('empresa')
    # ### end Alembic commands ###
