"""add data_assinatura to contrato

Revision ID: a5aa13136de9
Revises: 1143c7e56630
Create Date: 2025-06-30 17:09:30.632404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5aa13136de9'
down_revision = '1143c7e56630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_assinatura', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('data_assinatura')

    # ### end Alembic commands ###
